apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: your-component-name
  description: A brief description of your component
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: your-team-name
